name: Docker Build Push

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Node.js and run tests
        uses: actions/setup-node@v3.6.0
      - name: Build Node.js packages
        run: npm ci
      - name: Build project dist
        run: npm run build --prod
      - name: Build docker image
        run: docker build . -t jasonwang101/portfolio:latest
      - name: Push docker image
        run: docker push jasonwang101/portfolio:latest